<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv [
<!-- DTD for TV listings http://xmltv.cvs.sourceforge.net/viewvc/xmltv/xmltv/xmltv.dtd --><!ELEMENT tv (channel* , programme*)>
<!ATTLIST tv date CDATA #IMPLIED>
<!ATTLIST tv source-info-url CDATA #IMPLIED>
<!ATTLIST tv source-info-name CDATA #IMPLIED>
<!ATTLIST tv source-data-url CDATA #IMPLIED>
<!ATTLIST tv generator-info-name CDATA #IMPLIED>
<!ATTLIST tv generator-info-url CDATA #IMPLIED>
<!ELEMENT channel (display-name+ , icon* , url*)>
<!ATTLIST channel id CDATA #REQUIRED>
<!ELEMENT display-name (#PCDATA)>
<!ATTLIST display-name lang CDATA #IMPLIED>
<!ELEMENT url (#PCDATA)>
<!ELEMENT programme (title+ , sub-title* , desc* , credits? , date? , category* , keyword* , language? , orig-language? , length? , icon* , url* , country* , episode-num* , video? , audio? , previously-shown? , premiere? , last-chance? , new? , subtitles* , rating* , star-rating* , review*)>
<!ATTLIST programme start CDATA #REQUIRED>
<!ATTLIST programme stop CDATA #IMPLIED>
<!ATTLIST programme pdc-start CDATA #IMPLIED>
<!ATTLIST programme vps-start CDATA #IMPLIED>
<!ATTLIST programme showview CDATA #IMPLIED>
<!ATTLIST programme videoplus CDATA #IMPLIED>
<!ATTLIST programme channel CDATA #REQUIRED>
<!ATTLIST programme clumpidx CDATA "0/1">
<!ELEMENT title (#PCDATA)>
<!ATTLIST title lang CDATA #IMPLIED>
<!ELEMENT sub-title (#PCDATA)>
<!ATTLIST sub-title lang CDATA #IMPLIED>
<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc lang CDATA #IMPLIED>
<!ELEMENT credits (director* , actor* , writer* , adapter* , producer* , composer* , editor* , presenter* , commentator* , guest*)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ATTLIST actor role CDATA #IMPLIED>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT adapter (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT composer (#PCDATA)>
<!ELEMENT editor (#PCDATA)>
<!ELEMENT presenter (#PCDATA)>
<!ELEMENT commentator (#PCDATA)>
<!ELEMENT guest (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST category lang CDATA #IMPLIED>
<!ELEMENT keyword (#PCDATA)>
<!ATTLIST keyword lang CDATA #IMPLIED>
<!ELEMENT language (#PCDATA)>
<!ATTLIST language lang CDATA #IMPLIED>
<!ELEMENT orig-language (#PCDATA)>
<!ATTLIST orig-language lang CDATA #IMPLIED>
<!ELEMENT length (#PCDATA)>
<!ATTLIST length units (seconds | minutes | hours) #REQUIRED>
<!ELEMENT icon EMPTY>
<!ATTLIST icon src CDATA #REQUIRED>
<!ATTLIST icon width CDATA #IMPLIED>
<!ATTLIST icon height CDATA #IMPLIED>
<!ELEMENT value (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ATTLIST country lang CDATA #IMPLIED>
<!ELEMENT episode-num (#PCDATA)>
<!ATTLIST episode-num system CDATA "onscreen">
<!ELEMENT video (present? , colour? , aspect? , quality?)>
<!ELEMENT present (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT aspect (#PCDATA)>
<!ELEMENT quality (#PCDATA)>
<!ELEMENT audio (present? , stereo?)>
<!ELEMENT stereo (#PCDATA)>
<!ELEMENT previously-shown EMPTY>
<!ATTLIST previously-shown start CDATA #IMPLIED>
<!ATTLIST previously-shown channel CDATA #IMPLIED>
<!ELEMENT premiere (#PCDATA)>
<!ATTLIST premiere lang CDATA #IMPLIED>
<!ELEMENT last-chance (#PCDATA)>
<!ATTLIST last-chance lang CDATA #IMPLIED>
<!ELEMENT new EMPTY>
<!ELEMENT subtitles (language)?>
<!ATTLIST subtitles type (teletext | onscreen | deaf-signed) #IMPLIED>
<!ELEMENT rating (value , icon*)>
<!ATTLIST rating system CDATA #IMPLIED>
<!ELEMENT star-rating (value , icon*)>
<!ATTLIST star-rating system CDATA #IMPLIED>
<!ELEMENT review (#PCDATA)>
<!ATTLIST review type (text | url) #REQUIRED>
<!ATTLIST review source CDATA #IMPLIED>
<!ATTLIST review reviewer CDATA #IMPLIED>
<!ATTLIST review lang CDATA #IMPLIED>
]>
<tv source-info-name="" source-info-url="" source-data-url="" generator-info-name="jaylinski/xmltv" generator-info-url="https://github.com/jaylinski/xmltv">
  <channel id="vtv1">
    <display-name lang="en">VTV1 HD</display-name>
    <icon src="https://i.imgur.com/te4Rb7f.png" width="" height=""/>
  </channel>
  <channel id="vtv2">
    <display-name lang="en">VTV2 HD</display-name>
    <icon src="https://i.imgur.com/KmngEnt.png" width="" height=""/>
  </channel>
  <channel id="vtv3">
    <display-name lang="en">VTV3 HD</display-name>
    <icon src="https://i.imgur.com/yNiXZri.png" width="" height=""/>
  </channel>
  <channel id="vtv4">
    <display-name lang="en">VTV4 HD</display-name>
    <icon src="https://i.imgur.com/WG3Wi0q.png" width="" height=""/>
  </channel>
  <channel id="vtv5">
    <display-name lang="en">VTV5 HD</display-name>
    <icon src="https://i.imgur.com/lOvwbNQ.png" width="" height=""/>
  </channel>
  <channel id="vtv6">
    <display-name lang="en">VTV6 HD</display-name>
    <icon src="https://i.imgur.com/QI4bFvX.png" width="" height=""/>
  </channel>
  <channel id="vtv7">
    <display-name lang="en">VTV7 HD</display-name>
    <icon src="https://i.imgur.com/z8m5lWk.png" width="" height=""/>
  </channel>
  <channel id="vtv8">
    <display-name lang="en">VTV8 HD</display-name>
    <icon src="https://i.imgur.com/mIjvO6X.png" width="" height=""/>
  </channel>
  <channel id="vtv9">
    <display-name lang="en">VTV9 HD</display-name>
    <icon src="https://i.imgur.com/GDP5zVb.png" width="" height=""/>
  </channel>
  <channel id="axn">
    <display-name lang="en">AXN HD</display-name>
    <icon src="https://i.imgur.com/5Gtp7WP.png" width="" height=""/>
  </channel>
  <channel id="hbo">
    <display-name lang="en">HBO HD</display-name>
    <icon src="https://i.imgur.com/6YSLw8h.png" width="" height=""/>
  </channel>
  <channel id="max_by_hbo">
    <display-name lang="en">Max by HBO</display-name>
    <icon src="https://i.imgur.com/PklWJDL.png" width="" height=""/>
  </channel>
  <channel id="animal_planet">
    <display-name lang="en">Animal Planet</display-name>
    <icon src="https://i.imgur.com/9t7FsCk.png" width="" height=""/>
  </channel>
  <channel id="cartoon_network">
    <display-name lang="en">Cartoon Network HD</display-name>
    <icon src="https://i.imgur.com/nzvNMfP.png" width="" height=""/>
  </channel>
  <channel id="discovery_asia">
    <display-name lang="en">Discovery Asia HD</display-name>
    <icon src="https://i.imgur.com/blEhr2T.png" width="" height=""/>
  </channel>
  <channel id="discovery">
    <display-name lang="en">Discovery Channel HD</display-name>
    <icon src="https://i.imgur.com/fXuxFbz.png" width="" height=""/>
  </channel>
  <channel id="fox_life">
    <display-name lang="en">FOX Life</display-name>
    <icon src="https://i.imgur.com/8COzEQg.png" width="" height=""/>
  </channel>
  <channel id="fox_movies">
    <display-name lang="en">FOX Movies</display-name>
    <icon src="https://i.imgur.com/1bzBhnP.png" width="" height=""/>
  </channel>
  <channel id="fox_sports">
    <display-name lang="en">FOX Sports HD</display-name>
    <icon src="https://i.imgur.com/JsFd6Nl.png" width="" height=""/>
  </channel>
  <channel id="fox_sports2">
    <display-name lang="en">FOX Sports 2 HD</display-name>
    <icon src="https://i.imgur.com/acCilxO.png" width="" height=""/>
  </channel>
  <channel id="fox_sports3">
    <display-name lang="en">FOX Sports 3 HD</display-name>
    <icon src="https://i.imgur.com/dhRuUbt.png" width="" height=""/>
  </channel>
  <channel id="disney_channel">
    <display-name lang="en">Disney Channel</display-name>
    <icon src="https://i.imgur.com/06F6gjj.png" width="" height=""/>
  </channel>
  <channel id="disney_junior">
    <display-name lang="en">Disney Junior</display-name>
    <icon src="https://i.imgur.com/ZUBEPXt.png" width="" height=""/>
  </channel>
  <channel id="mtv_asia">
    <display-name lang="en">MTV Asia</display-name>
    <icon src="https://i.imgur.com/gpWosop.png" width="" height=""/>
  </channel>
  <channel id="channel_v">
    <display-name lang="en">Channel V</display-name>
    <icon src="https://i.imgur.com/DdyyACT.png" width="" height=""/>
  </channel>
  <channel id="diva">
    <display-name lang="en">DIVA</display-name>
    <icon src="https://i.imgur.com/OJNm5Vt.png" width="" height=""/>
  </channel>
  <channel id="da_vinci_kids">
    <display-name lang="en">Da Vinci Kids</display-name>
    <icon src="https://i.imgur.com/ZkEEeM9.png" width="" height=""/>
  </channel>
  <channel id="asian_food_channel">
    <display-name lang="en">Asian Food Channel</display-name>
    <icon src="https://i.imgur.com/rQ3Sgrn.png" width="" height=""/>
  </channel>
  <channel id="outdoor_channel">
    <display-name lang="en">Outdoor Channel</display-name>
    <icon src="https://i.imgur.com/Z3xc8p1.png" width="" height=""/>
  </channel>
  <channel id="fashion_tv">
    <display-name lang="en">Fashion TV</display-name>
    <icon src="https://i.imgur.com/Zyy11Cs.png" width="" height=""/>
  </channel>
  <channel id="fox">
    <display-name lang="en">FOX HD</display-name>
    <icon src="https://i.imgur.com/cwVCPqN.png" width="" height=""/>
  </channel>
  <channel id="national_geographic">
    <display-name lang="en">National Geographic HD</display-name>
    <icon src="https://i.imgur.com/cjx78kt.png" width="" height=""/>
  </channel>
  <channel id="blue_ant_entertainment">
    <display-name lang="en">Blue Ant Entertainment</display-name>
    <icon src="https://i.imgur.com/BaZuGNL.png" width="" height=""/>
  </channel>
  <channel id="blue_ant_extreme">
    <display-name lang="en">Blue Ant Extreme</display-name>
    <icon src="https://i.imgur.com/EUHDtZ5.png" width="" height=""/>
  </channel>
  <channel id="warner_tv_hd">
    <display-name lang="en">Warner TV HD</display-name>
    <icon src="https://i.imgur.com/z8Cm35k.png" width="" height=""/>
  </channel>
  <channel id="tlc">
    <display-name lang="en">TLC (Travel &amp; Living)</display-name>
    <icon src="https://i.imgur.com/amlBPub.png" width="" height=""/>
  </channel>
  <channel id="red_by_hbo">
    <display-name lang="en">Red by HBO</display-name>
    <icon src="https://i.imgur.com/S3LHf04.png" width="" height=""/>
  </channel>
  <channel id="nhk_world">
    <display-name lang="en">NHK World</display-name>
    <icon src="https://i.imgur.com/5fKRgDE.png" width="" height=""/>
  </channel>
  <channel id="bbc_earth">
    <display-name lang="en">BBC EARTH</display-name>
    <icon src="https://i.imgur.com/3sQunND.png" width="" height=""/>
  </channel>
  <channel id="bbc_lifestyle">
    <display-name lang="en">BBC LIFESTYLE</display-name>
    <icon src="https://i.imgur.com/wwTUVYP.png" width="" height=""/>
  </channel>
  <channel id="bbc_world_news">
    <display-name lang="en">BBC WORLD NEWS</display-name>
    <icon src="https://i.imgur.com/9ZqIRg1.png" width="" height=""/>
  </channel>
  <channel id="baby_tv_hd">
    <display-name lang="en">Baby TV HD</display-name>
    <icon src="https://i.imgur.com/s28XuHs.png" width="" height=""/>
  </channel>
  <channel id="abc_australia">
    <display-name lang="en">ABC AUSTRALIA</display-name>
    <icon src="https://i.imgur.com/0OrWtJm.png" width="" height=""/>
  </channel>
  <channel id="kix_hd">
    <display-name lang="en">KIX HD</display-name>
    <icon src="https://i.imgur.com/CVxACz9.png" width="" height=""/>
  </channel>
  <channel id="cinema_world_hd">
    <display-name lang="en">CINEMA WORLD HD</display-name>
    <icon src="https://i.imgur.com/KcEAjUh.png" width="" height=""/>
  </channel>
  <channel id="htv1">
    <display-name lang="en">HTV1</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htv2">
    <display-name lang="en">HTV2 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htv3">
    <display-name lang="en">HTV3</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htv4">
    <display-name lang="en">HTV4</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htv7">
    <display-name lang="en">HTV7 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htv9">
    <display-name lang="en">HTV9 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htvc_phim_hd">
    <display-name lang="en">HTVC Phim HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htvc_gia_dinh">
    <display-name lang="en">HTVC Gia Đình</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htvc_du_lich_cuoc_song">
    <display-name lang="en">HTVC Du Lịch &amp; Đời Sống</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htvc_phu_nu">
    <display-name lang="en">HTVC Phụ Nữ</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htvc_thuan_viet_hd">
    <display-name lang="en">HTVC Thuần Việt HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htvc_thuan_viet">
    <display-name lang="en">HTVC Thuần Việt</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htvc_fbnc">
    <display-name lang="en">FBNC HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htvc_coop">
    <display-name lang="en">HTVC CO.OP</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htv_the_thao">
    <display-name lang="en">HTV Thể Thao</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="htvc_vgs_shop">
    <display-name lang="en">HTVC VGS SHOP</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc1">
    <display-name lang="en">VTC1 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc2">
    <display-name lang="en">VTC2 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc3">
    <display-name lang="en">VTC3 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc4_yeah1_family">
    <display-name lang="en">VTC4 Yeah1 Family HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc5">
    <display-name lang="en">VTC5 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc6">
    <display-name lang="en">VTC6 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc7_today_tv">
    <display-name lang="en">VTC7 Today TV HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc8">
    <display-name lang="en">VTC8</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc9_lets_viet">
    <display-name lang="en">VTC9 Let's Viet HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc10">
    <display-name lang="en">VTC10 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc11_kids_tv">
    <display-name lang="en">VTC11 Kids TV</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc12">
    <display-name lang="en">VTC12</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc13">
    <display-name lang="en">VTC13 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc14">
    <display-name lang="en">VTC14 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vtc16">
    <display-name lang="en">VTC16 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="thvl1">
    <display-name lang="en">THVL1 - Vĩnh Long 1 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="thvl2">
    <display-name lang="en">THVL2 - Vĩnh Long 2 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="thvl3">
    <display-name lang="en">THVL3- Vĩnh Long 3 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="ttxvn">
    <display-name lang="en">TTXVN - Thông Tấn Xã VN HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="antv">
    <display-name lang="en">ANTV - An Ninh TV HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="nhan_dan_tv">
    <display-name lang="en">Nhân Dân TV HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="quoc_hoi_tv">
    <display-name lang="en">Quốc Hội TV HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="quoc_phong_tv">
    <display-name lang="en">QPTV - Quốc Phòng VN HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="sctv10">
    <display-name lang="en">SCTV10</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="btv9_an_vien">
    <display-name lang="en">BTV9 - An Viên HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="btv6_viet_teen">
    <display-name lang="en">BTV6 - Việt Teen</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="btv10_ncm">
    <display-name lang="en">BTV10 - NCM</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="btv11_sam">
    <display-name lang="en">BTV11 - SAM</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="hanoitv1">
    <display-name lang="en">Hà Nội 1 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="hanoitv2">
    <display-name lang="en">Hà Nội 2 HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="arirang">
    <display-name lang="en">Arirang</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="cnbc">
    <display-name lang="en">CNBC</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="cnn">
    <display-name lang="en">CNN</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="vovtv">
    <display-name lang="en">VOV TV</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="hbo">
    <display-name lang="en">HBO HD</display-name>
    <icon src="https://i.imgur.com/6YSLw8h.png" width="" height=""/>
  </channel>
  <channel id="btv4_imovie">
    <display-name lang="en">BTV4 iMovies HD</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <channel id="sctv2">
    <display-name lang="en">SCTV2</display-name>
    <icon src="" width="" height=""/>
  </channel>
  <programme start="20190905001500" stop="20190905011000" channel="animal_planet">
    <title lang="en">ANIMAL NATION WITH ANTHONY ANDERSON : VƯƠNG QUỐC ĐỘNG VẬT DẪN CHƯƠNG TRÌNH: ANTHONY ANDERSON</title>
    <desc lang="en">ANIMAL NATION WITH ANTHONY ANDERSON : VƯƠNG QUỐC ĐỘNG VẬT DẪN CHƯƠNG TRÌNH: ANTHONY ANDERSON</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905011000" stop="20190905020500" channel="animal_planet">
    <title lang="en">WORLD'S CUTEST : NHỮNG SINH VẬT ĐÁNG YÊU NHẤT THẾ GIỚI</title>
    <desc lang="en">WORLD'S CUTEST : NHỮNG SINH VẬT ĐÁNG YÊU NHẤT THẾ GIỚI</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905020500" stop="20190905023000" channel="animal_planet">
    <title lang="en">HOW DO ANIMALS DO THAT? : TẠI SAO ĐỘNG VẬT LẠI THẾ?</title>
    <desc lang="en">HOW DO ANIMALS DO THAT? : TẠI SAO ĐỘNG VẬT LẠI THẾ?</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905023000" stop="20190905030000" channel="animal_planet">
    <title lang="en">HOW DO ANIMALS DO THAT? : TẠI SAO ĐỘNG VẬT LẠI THẾ?</title>
    <desc lang="en">HOW DO ANIMALS DO THAT? : TẠI SAO ĐỘNG VẬT LẠI THẾ?</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905030000" stop="20190905035500" channel="animal_planet">
    <title lang="en">MY CAT FROM HELL (S9) : MÈO CỦA TÔI ĐẾN TỪ ĐỊA NGỤC (PHẦN 9)</title>
    <desc lang="en">MY CAT FROM HELL (S9) : MÈO CỦA TÔI ĐẾN TỪ ĐỊA NGỤC (PHẦN 9)</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905035500" stop="20190905045000" channel="animal_planet">
    <title lang="en">MY CAT FROM HELL (S8) : MÈO CỦA TÔI TỚI TỪ ĐỊA NGỤC</title>
    <desc lang="en">MY CAT FROM HELL (S8) : MÈO CỦA TÔI TỚI TỪ ĐỊA NGỤC</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905045000" stop="20190905054500" channel="animal_planet">
    <title lang="en">ATTACK OF THE KILLER DRAGONS : CUỘC TẤN CÔNG CỦA RỒNG SÁT THỦ</title>
    <desc lang="en">ATTACK OF THE KILLER DRAGONS : CUỘC TẤN CÔNG CỦA RỒNG SÁT THỦ</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905054500" stop="20190905064000" channel="animal_planet">
    <title lang="en">WORLD'S CUTEST : NHỮNG SINH VẬT ĐÁNG YÊU NHẤT THẾ GIỚI</title>
    <desc lang="en">WORLD'S CUTEST : NHỮNG SINH VẬT ĐÁNG YÊU NHẤT THẾ GIỚI</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905064000" stop="20190905070500" channel="animal_planet">
    <title lang="en">HOW DO ANIMALS DO THAT? : TẠI SAO ĐỘNG VẬT LẠI THẾ?</title>
    <desc lang="en">HOW DO ANIMALS DO THAT? : TẠI SAO ĐỘNG VẬT LẠI THẾ?</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905070500" stop="20190905073500" channel="animal_planet">
    <title lang="en">HOW DO ANIMALS DO THAT? : TẠI SAO ĐỘNG VẬT LẠI THẾ?</title>
    <desc lang="en">HOW DO ANIMALS DO THAT? : TẠI SAO ĐỘNG VẬT LẠI THẾ?</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905073500" stop="20190905083000" channel="animal_planet">
    <title lang="en">MY CAT FROM HELL (S9) : MÈO CỦA TÔI ĐẾN TỪ ĐỊA NGỤC (PHẦN 9)</title>
    <desc lang="en">MY CAT FROM HELL (S9) : MÈO CỦA TÔI ĐẾN TỪ ĐỊA NGỤC (PHẦN 9)</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905083000" stop="20190905092500" channel="animal_planet">
    <title lang="en">RUGGED JUSTICE (S3) : CÔNG LÝ GIAN NAN (PHẦN 3)</title>
    <desc lang="en">RUGGED JUSTICE (S3) : CÔNG LÝ GIAN NAN (PHẦN 3)</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905092500" stop="20190905102000" channel="animal_planet">
    <title lang="en">MONSTERS INSIDE ME (S5) : QUÁI VẬT TRONG TÔI (PHẦN 5)</title>
    <desc lang="en">MONSTERS INSIDE ME (S5) : QUÁI VẬT TRONG TÔI (PHẦN 5)</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905102000" stop="20190905111500" channel="animal_planet">
    <title lang="en">AMERICA'S CUTEST (S5) : NHỮNG SINH VẬT ĐÁNG YÊU NHẤT NƯỚC MỸ (PHẦN 5)</title>
    <desc lang="en">AMERICA'S CUTEST (S5) : NHỮNG SINH VẬT ĐÁNG YÊU NHẤT NƯỚC MỸ (PHẦN 5)</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905111500" stop="20190905121000" channel="animal_planet">
    <title lang="en">MY CAT FROM HELL (S8) : MÈO CỦA TÔI TỚI TỪ ĐỊA NGỤC</title>
    <desc lang="en">MY CAT FROM HELL (S8) : MÈO CỦA TÔI TỚI TỪ ĐỊA NGỤC</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905121000" stop="20190905130500" channel="animal_planet">
    <title lang="en">WEIRD CREATURES WITH NICK BAKER (S3) : NHỮNG SINH VẬT KỲ LẠ DẪN CHƯƠNG TRÌNH: NICK BAKER (PHẦN 3)</title>
    <desc lang="en">WEIRD CREATURES WITH NICK BAKER (S3) : NHỮNG SINH VẬT KỲ LẠ DẪN CHƯƠNG TRÌNH: NICK BAKER (PHẦN 3)</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905130500" stop="20190905140000" channel="animal_planet">
    <title lang="en">EXPEDITION MUNGO : THÁM HIỂM CÙNG MUNGO</title>
    <desc lang="en">EXPEDITION MUNGO : THÁM HIỂM CÙNG MUNGO</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905140000" stop="20190905145500" channel="animal_planet">
    <title lang="en">DR. JEFF: ROCKY MOUNTAIN VET (S5) : BÁC SĨ JEFF: BÁC SĨ THÚ Y NÚI ROCKY</title>
    <desc lang="en">DR. JEFF: ROCKY MOUNTAIN VET (S5) : BÁC SĨ JEFF: BÁC SĨ THÚ Y NÚI ROCKY</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905145500" stop="20190905155000" channel="animal_planet">
    <title lang="en">TANKED (S8) : LÀM BỂ (PHẦN 8)</title>
    <desc lang="en">TANKED (S8) : LÀM BỂ (PHẦN 8)</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905155000" stop="20190905164500" channel="animal_planet">
    <title lang="en">MONSTERS INSIDE ME (S5) : QUÁI VẬT TRONG TÔI (PHẦN 5)</title>
    <desc lang="en">MONSTERS INSIDE ME (S5) : QUÁI VẬT TRONG TÔI (PHẦN 5)</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190905164500" stop="20190904174000" channel="animal_planet">
    <title lang="en">EXPEDITION MUNGO : THÁM HIỂM CÙNG MUNGO</title>
    <desc lang="en">EXPEDITION MUNGO : THÁM HIỂM CÙNG MUNGO</desc>
    <date>20190905</date>
  </programme>
  <programme start="20190902174000" stop="20190902183500" channel="animal_planet">
    <title lang="en">DODO HEROES (S2) : NHỮNG NGƯỜI HÙNG CỦA DODO (PHẦN 2)</title>
    <desc lang="en">DODO HEROES (S2) : NHỮNG NGƯỜI HÙNG CỦA DODO (PHẦN 2)</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190902183500" stop="20190902193000" channel="animal_planet">
    <title lang="en">JEREMY WADE'S MIGHTY RIVERS : NHỮNG CON SÔNG HÙNG VĨ DẪN CHƯƠNG TRÌNH: JEREMY WADE</title>
    <desc lang="en">JEREMY WADE'S MIGHTY RIVERS : NHỮNG CON SÔNG HÙNG VĨ DẪN CHƯƠNG TRÌNH: JEREMY WADE</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190902193000" stop="20190902202500" channel="animal_planet">
    <title lang="en">ANIMAL NATION WITH ANTHONY ANDERSON : VƯƠNG QUỐC ĐỘNG VẬT DẪN CHƯƠNG TRÌNH: ANTHONY ANDERSON</title>
    <desc lang="en">ANIMAL NATION WITH ANTHONY ANDERSON : VƯƠNG QUỐC ĐỘNG VẬT DẪN CHƯƠNG TRÌNH: ANTHONY ANDERSON</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190902202500" stop="20190902212000" channel="animal_planet">
    <title lang="en">MONSTERS INSIDE ME (S5) : QUÁI VẬT TRONG TÔI (PHẦN 5)</title>
    <desc lang="en">MONSTERS INSIDE ME (S5) : QUÁI VẬT TRONG TÔI (PHẦN 5)</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190902212000" stop="20190902221500" channel="animal_planet">
    <title lang="en">AMANDA TO THE RESCUE : AMANDA ĐẾN GIẢI CỨU</title>
    <desc lang="en">AMANDA TO THE RESCUE : AMANDA ĐẾN GIẢI CỨU</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190902221500" stop="20190902231500" channel="animal_planet">
    <title lang="en">WILDEST SURVIVAL : PHƯƠNG THỨC SINH TỒN HOANG DÃ NHẤT</title>
    <desc lang="en">WILDEST SURVIVAL : PHƯƠNG THỨC SINH TỒN HOANG DÃ NHẤT</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190902231500" stop="20190903001500" channel="animal_planet">
    <title lang="en">RUGGED JUSTICE (S3) : CÔNG LÝ GIAN NAN (PHẦN 3)</title>
    <desc lang="en">RUGGED JUSTICE (S3) : CÔNG LÝ GIAN NAN (PHẦN 3)</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903001500" stop="20190903011000" channel="animal_planet">
    <title lang="en">ANIMAL NATION WITH ANTHONY ANDERSON : VƯƠNG QUỐC ĐỘNG VẬT DẪN CHƯƠNG TRÌNH: ANTHONY ANDERSON</title>
    <desc lang="en">ANIMAL NATION WITH ANTHONY ANDERSON : VƯƠNG QUỐC ĐỘNG VẬT DẪN CHƯƠNG TRÌNH: ANTHONY ANDERSON</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903011000" stop="20190903020500" channel="animal_planet">
    <title lang="en">HANGING WITH THE HENDERSONS : GIAO LƯU VỚI NHÀ HENDERSON</title>
    <desc lang="en">HANGING WITH THE HENDERSONS : GIAO LƯU VỚI NHÀ HENDERSON</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903020500" stop="20190903030000" channel="animal_planet">
    <title lang="en">DODO HEROES (S2) : NHỮNG NGƯỜI HÙNG CỦA DODO (PHẦN 2)</title>
    <desc lang="en">DODO HEROES (S2) : NHỮNG NGƯỜI HÙNG CỦA DODO (PHẦN 2)</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903030000" stop="20190903035500" channel="animal_planet">
    <title lang="en">JEREMY WADE'S MIGHTY RIVERS : NHỮNG CON SÔNG HÙNG VĨ DẪN CHƯƠNG TRÌNH: JEREMY WADE</title>
    <desc lang="en">JEREMY WADE'S MIGHTY RIVERS : NHỮNG CON SÔNG HÙNG VĨ DẪN CHƯƠNG TRÌNH: JEREMY WADE</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903035500" stop="20190903045000" channel="animal_planet">
    <title lang="en">AMANDA TO THE RESCUE : AMANDA ĐẾN GIẢI CỨU</title>
    <desc lang="en">AMANDA TO THE RESCUE : AMANDA ĐẾN GIẢI CỨU</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903045000" stop="20190903054500" channel="animal_planet">
    <title lang="en">WILDEST SURVIVAL : PHƯƠNG THỨC SINH TỒN HOANG DÃ NHẤT</title>
    <desc lang="en">WILDEST SURVIVAL : PHƯƠNG THỨC SINH TỒN HOANG DÃ NHẤT</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903054500" stop="20190903064000" channel="animal_planet">
    <title lang="en">HANGING WITH THE HENDERSONS : GIAO LƯU VỚI NHÀ HENDERSON</title>
    <desc lang="en">HANGING WITH THE HENDERSONS : GIAO LƯU VỚI NHÀ HENDERSON</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903064000" stop="20190903073500" channel="animal_planet">
    <title lang="en">DODO HEROES (S2) : NHỮNG NGƯỜI HÙNG CỦA DODO (PHẦN 2)</title>
    <desc lang="en">DODO HEROES (S2) : NHỮNG NGƯỜI HÙNG CỦA DODO (PHẦN 2)</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903073500" stop="20190903083000" channel="animal_planet">
    <title lang="en">JEREMY WADE'S MIGHTY RIVERS : NHỮNG CON SÔNG HÙNG VĨ DẪN CHƯƠNG TRÌNH: JEREMY WADE</title>
    <desc lang="en">JEREMY WADE'S MIGHTY RIVERS : NHỮNG CON SÔNG HÙNG VĨ DẪN CHƯƠNG TRÌNH: JEREMY WADE</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903083000" stop="20190903092500" channel="animal_planet">
    <title lang="en">RUGGED JUSTICE (S3) : CÔNG LÝ GIAN NAN (PHẦN 3)</title>
    <desc lang="en">RUGGED JUSTICE (S3) : CÔNG LÝ GIAN NAN (PHẦN 3)</desc>
    <date>20190903</date>
  </programme>
  <programme start="20190903092500" stop="20190903102000" channel="animal_planet">
    <title lang="en">MONSTERS INSIDE ME (S5) : QUÁI VẬT TRONG TÔI (PHẦN 5)</title>
    <desc lang="en">MONSTERS INSIDE ME (S5) : QUÁI VẬT TRONG TÔI (PHẦN 5)</desc>
    <date>20190903</date>
  </programme>